spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
  thymeleaf:
    cache: false
#  配置国际化
  messages:
    basename: i18n.login
#  日期格式
  mvc:
    date-format: yyyy-MM-dd

#配置邮件发送
  mail:
    host: smtp.163.com
    username: bgdragon@163.com
    password: ARFOJLGXYAWWQQBD

server:
  port: 8085

#配置mybatisplus打印输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
swagger:
  enable: true
