spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver

  thymeleaf:
    cache: false
#  配置国际化
  messages:
    basename: i18n.login
server:
  port: 8081

#配置mybatisplus打印输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl